name: Build APK

on:
  push:
    branches:
      - main      # Trigger on push to the main branch (or any other release branch)       # Optionally, trigger on version tags like v1.0.0, v2.0.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4
    
      # Set up JDK 11 (Android development requires JDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: gradle

      # Grant execute permissions for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
    
      # Build the APK with Gradle (you can use assembleRelease or assembleDebug based on your needs)
      - name: Build APK
        run: ./gradlew assembleRelease   # Builds APK in release mode. Change to assembleDebug for a debug build

      # Upload APK as artifact (Optional step to store the APK)
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk  # The path to the built APK file

